### ISSUE TITLE
keys *提示错误： (error) ERR proxy command not support

### ISSUE THREAD

**Issue by OPSTime** [netease-im/camellia#264]
通过docker-compose部署启动两个redis，master、slave及一个proxy，通过proxy执行“keys *"命令提示不支持，看如下文档中说是支持keys，条件是：only support while have singleton-upstream(no custom sharding) (redis-standalone or redis-sentinel)
https://github.com/netease-im/camellia/blob/master/docs/redis-proxy/supported_commands.md

但看standalone_mode文档只有一张图 没有具体如何配置
https://github.com/netease-im/camellia/blob/master/docs/redis-proxy/deploy/standalone_mode.md

也找到resource-table.json、application.yml配置文件中详细说明文档

请问具体如何配置才能支持“keys *”

**错误：**
```
127.0.0.1:6380> keys *
(error) ERR proxy command not support
```

**具体配置：**
cat resource-table.json
```
{
  "type": "simple",
  "operation": {
    "read": "redis://@192.168.2.22:36379",
    "type": "rw_separate",
    "write": "redis://@192.168.2.22:26379",
  }
}
```

cat application.yml 
```
server:
  port: 6380
spring:
  application:
    name: camellia-redis-proxy-server
camellia-redis-proxy:
  console-port: 16379 
  monitor-enable: true
  monitor-interval-seconds: 60 
  plugins: 
    - monitorPlugin
    - bigKeyPlugin
    - hotKeyPlugin
  transpond:
    type: local 
    local:
      type: complex
      json-file: resource-table.json

```
