### ISSUE TITLE
troubleTrickKeys doc fix

### ISSUE THREAD

**Issue by lirulei** [netease-im/camellia#316]
Module: [camellia-redis-proxy]
Version: [v1.2.29 ]
Content: [e.g. doc has a error]

https://github.com/netease-im/camellia/blob/master/docs/camellia-redis-proxy/plugin/trouble-trick-keys.md

the config file application.yml , **plugins** field has a error，the correct config like this：
```
server:
  port: 6380
spring:
  application:
    name: camellia-redis-proxy-server

camellia-redis-proxy:
  console-port: 16379 #console端口，默认是16379，如果设置为-16379则会随机一个可用端口，如果设置为0，则不启动console
  password: pass123   #proxy的密码，如果设置了自定义的client-auth-provider-class-name，则密码参数无效
  monitor-enable: true  #是否开启监控
  monitor-interval-seconds: 60 #监控回调的间隔
  plugins: #使用yml配置插件，内置插件可以直接使用别名启用，自定义插件需要配置全类名
    - troubleTrickKeysPlugin  
  transpond:
    type: local #使用本地配置
    local:
      type: simple
      resource: redis://@127.0.0.1:6379 #转发的redis地址
```

also，the config file **camellia-redis-proxy.properties** , proxy.plugin.list field has a error,the correct config like this：
```
proxy.plugin.list=troubleTrickKeysPlugin
```
