### ISSUE TITLE
RedisClusterSlotInfo Initialization Failure in Camellia Redis Proxy

### ISSUE THREAD

**Issue by TZ1414** [netease-im/camellia#352]
在将 Camellia Redis Proxy 配置为连接到 Redis 集群并启动应用程序时，RedisClusterSlotInfo 的初始化过程出现错误。应用程序启动失败，并显示以下错误信息：

**Comment by TZ1414** [comment]
报错信息：
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisProxyBoot' defined in class path resource [com/netease/nim/camellia/redis/proxy/springboot/CamelliaRedisProxyConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netease.nim.camellia/redis/proxy/springboot.CamelliaRedisProxyBoot]: Factory method 'redisProxyBoot' threw exception; nested exception is com.netease.nim.camellia.redis.base.exception.CamelliaRedisException: RedisClusterSlotInfo init fail, resource = redis-cluster://@xx.xx.xx.xx:7000,xx.xx.xx.xx:7001,xx.xx.xx.xx:7000,xx.xx.xx.xx:7001,xx.xx.xx.xx:7000,xx.xx.xx.xx:7001`

配置文件：
```
camellia-redis-proxy:
  transpond:
    type: local
    local:
      type: simple
      resource: redis-cluster://@xx.xx.xx.xx:7000,xx.xx.xx.xx:7001,xx.xx.xx.xx:7000,xx.xx.xx.xx:7001,xx.xx.xx.xx:7000,xx.xx.xx.xx:7001
```
