### ISSUE TITLE
[Camellia-redis-proxy] How to add a custom header into CamelliaApi: api-key

### ISSUE THREAD

**Issue by tasszz2k** [netease-im/camellia#48]
`Camellia-dashboard`: I implement `api-key authentication`. Every request must have the header `api-key: xxx` for more security.

`Camellia-redis-proxy`: I don't want to modify your code, how can I override `Request Interceptor` of [CamelliaApi](https://github.com/netease-im/camellia/blob/master/camellia-core/src/main/java/com/netease/nim/camellia/core/api/CamelliaApi.java) (2 methods: `getResourceTable()` , `reportStats()`)

I saw your code init `Camellia Feign Client` inside `CamelliaApiUtil`:

```java
public class CamelliaApiUtil {

    public static CamelliaApi init(String url, int connectTimeoutMillis, int readTimeoutMillis) {
        return Feign.builder()
                .encoder(new JacksonEncoder())
                .decoder(new JacksonDecoder())
                .requestInterceptor(template -> {
                    if (CamelliaApiEnv.source != null) {
                        template.header(CamelliaApiEnv.REQUEST_SOURCE, CamelliaApiEnv.source);
                    }
                })
                .options(new Request.Options(connectTimeoutMillis, readTimeoutMillis))
                .target(CamelliaApi.class, url);
    }
}
``` 
But it is not Bean, so I cannot override it or add Request Interceptor like that:

```java
    @Bean
    public RequestInterceptor myCustomInterceptor() {
        return template->template.header("api-key", "xxx");
    }
```
----
I suggest a feature that we can config headers inside transpond `RemoteProperties`:

application.yaml
```yaml
camellia-redis-proxy:
  transpond:
    type: remote
    remote: 
      url: ${CAMELLIA_DASHBOARD_URL:http://127.0.0.1:8080} #camellia-dashboard's address
      check-interval-millis: ${REMOTE_CHECK_INTERVAL_MILLIS:5000} # Polling period to camellia-dashboard
      dynamic: ${REMOTE_DYNAMIC:true} # indicates that multiple sets of configurations are supported, the default is true
      api-key-header-name: ${REMOTE_API_KEY_HEADER_NAME:api-key} # API Key header name
      api-key: ${REMOTE_API_KEY:xxx} # API Key
```
 
And add it inside :
```java
public class CamelliaApiUtil {

    public static CamelliaApi init(String url, String apiKeyHeaderName, String apiKey, int connectTimeoutMillis, int readTimeoutMillis) {
        return Feign.builder()
                .encoder(new JacksonEncoder())
                .decoder(new JacksonDecoder())
                .requestInterceptor(template -> {
                    if (CamelliaApiEnv.source != null) {
                        template.header(CamelliaApiEnv.REQUEST_SOURCE, CamelliaApiEnv.source);
                    }
                    if(apiKeyHeaderName != null){ // <-------------------------------------------this
                        template.header(apiKeyHeaderName, apiKey);
                    }
                })
                .options(new Request.Options(connectTimeoutMillis, readTimeoutMillis))
                .target(CamelliaApi.class, url);
    }
}
```
