### ISSUE TITLE
Support for selecting other database by redis-proxy

### ISSUE THREAD

**Issue by rysi3k** [netease-im/camellia#60]
Hello
Could someone explain why there is no support for selecting other database than 0?

Or maybe it is possible to get some workaround by setup database in "resource-table.json" file and launch few instances of redis-proxy (db0 on port 6000, db1 on port 6001 etc)?
For example, something like that:
```
server:
  port: 6002
spring:
  application:
    name: camellia-redis-proxy-server

camellia-redis-proxy:
  database: 2 # <---- here setup database id that is supported, default=0
  transpond:
    type: local
    local:
      type: complex
      json-file: /tmp/resource-table.json
```

and:
```
{
  "type": "simple",
  "operation": {
    "read": "redis://passwd1@127.0.0.1:6379/2", # <--- here is "destination" database id
    "type": "rw_separate",
    "write": {
      "resources": [
        "redis://passwd1@127.0.0.1:6379/2", # <--- here is "destination" database id
        "redis://passwd2@127.0.0.1:6380/2", # <--- here is "destination" database id
      ],
      "type": "multi"
    }
  }
}
```

Thanks for help

**Comment by caojiajun** [comment]
it's a good suggestion. 

redis-cluster only support db0, so camellia will support select db on redis-standalone or redis-sentinel, such as:

```
redis://passwd@127.0.0.1:6379?db=1
redis-sentinel://passwd@127.0.0.1:16379,127.0.0.1:26379/myMaster?db=1
redis-sentinel-slaves://passwd@127.0.0.1:16379,127.0.0.1:26379/myMaster?withMaster=true&db=1
```

this feature will provide in 1.1.7

**Comment by caojiajun** [comment]
the code of this feature has committed, you can check and try

**Comment by tasszz2k** [comment]
@caojiajun I have a question 
Does `camellia-dashboard` support select DB on redis?

```yaml
...

camellia-redis:
  type: local
  local:
    resource: redis://passwd@127.0.0.1:6379?db=1
  redis-conf:
    jedis:
      max-idle: 10
      min-idle: 0
      max-active: 100
      max-wait-millis: 2000
      timeout: 2000
...
```
