### ISSUE TITLE
Feature: support prometheus/grafana for camellia-redis-proxy

### ISSUE THREAD

**Issue by caojiajun** [netease-im/camellia#66]
If you have similar needs, please leave a message in this issue.

**Comment by tasszz2k** [comment]
vote up +1

**Comment by tasszz2k** [comment]
Can we develop this feature and release it in the next version?
If I can support you, let's talk to me, bro

**Comment by caojiajun** [comment]
you can override StatsPromethusConverter.java as prometheus exportor
and define the grafana view for monitor data

**Comment by tasszz2k** [comment]
I saw that 👍 
But, can you write some samples and I will follow that to make it done?

I'm so grateful to you for all that you've done.

**Comment by caojiajun** [comment]
https://prometheus.io/docs/instrumenting/exposition_formats/

see `Text format example`

**Comment by tasszz2k** [comment]
- How to configure Prometheus?
- Which is the endpoint of the camellia-redis-proxy expose metrics?

```yaml
scrape_configs:
  - job_name: 'Camellia-redis-proxy'
    metrics_path: '/prometheus'  # -------> ?
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:16378']
        labels:
          application: 'Camellia Redis Proxy'
```

**Comment by tasszz2k** [comment]
Should we use this library https://github.com/prometheus/client_java?

**Comment by tasszz2k** [comment]
> * How to configure Prometheus?
> * Which is the endpoint of the camellia-redis-proxy expose metrics?
> 
> **prometheus.yaml**
> 
> ```yaml
> scrape_configs:
>   - job_name: 'Camellia-redis-proxy'
>     metrics_path: '/prometheus'  # -------> ?
>     scrape_interval: 3s
>     static_configs:
>       - targets: ['host.docker.internal:16378']
>         labels:
>           application: 'Camellia Redis Proxy'
> ```

I added endpoint `/prometheus` in the class `ConsoleServerHandler`.

**Comment by caojiajun** [comment]
> > * How to configure Prometheus?
> > * Which is the endpoint of the camellia-redis-proxy expose metrics?
> > 
> > **prometheus.yaml**
> > ```yaml
> > scrape_configs:
> >   - job_name: 'Camellia-redis-proxy'
> >     metrics_path: '/prometheus'  # -------> ?
> >     scrape_interval: 3s
> >     static_configs:
> >       - targets: ['host.docker.internal:16378']
> >         labels:
> >           application: 'Camellia Redis Proxy'
> > ```
> 
> I added endpoint `/prometheus` in the class `ConsoleServerHandler`.

its's right

**Comment by caojiajun** [comment]
> Should we use this library https://github.com/prometheus/client_java?

we can build the string as promethus style by ourself.

**Comment by caojiajun** [comment]
like this: 

```
camellia-redis-proxy:
  password: nimmixpasswd
  console-port: 16379
  monitor-enable: true
  monitor-interval-seconds: 60 #监控回调的间隔
  monitor-callback-class-name: com.netease.nim.camellia.redis.proxy.monitor.LoggingMonitorCallback #监控回调类
  plugins: #
    - monitorPlugin
    - bigKeyPlugin
    - hotKeyPlugin
    - hotKeyCachePlugin
  transpond:
    type: local
    local:
      resource: redis-cluster://@xxx

```
