### ISSUE TITLE
Feature: [Camellia-dashboard] support select database on camellia-redis.local.resource

### ISSUE THREAD

**Issue by tasszz2k** [netease-im/camellia#78]
### 1. Issue
- I try setting the `camellia-redis.local.resource` as `redis://passwd@127.0.0.1:6379?db=1` but seems `camellia-dashboard` always selects default DB (db=0)
- actual: db_0  vs db_2
<img width="567" alt="image" src="https://user-images.githubusercontent.com/48039235/209611097-abf23b0e-b73c-4b0d-8cea-60ebe09f8504.png">

### 2. Configurations
```yaml
...

camellia-redis:
  type: local
  local:
    resource: redis://passwd@127.0.0.1:6379?db=1
  redis-conf:
    jedis:
      max-idle: 10
      min-idle: 0
      max-active: 100
      max-wait-millis: 2000
      timeout: 2000
...
```
### 3. Expectation
-   `Camellia-dashboard` supports select database on `camellia-redis.local.resource`
- Issue Ref: https://github.com/netease-im/camellia/issues/60
