### ISSUE TITLE
Issue:  [Redis-proxy] ERR max number of clients + cluster connections reached

### ISSUE THREAD

**Issue by tasszz2k** [netease-im/camellia#82]
### 1. Issue
- I got many error logs that: `ERR max number of clients + cluster connections reached`
- The `camellia-redis-proxy` created ~10k connection to a redis cluster ??? 
![image](https://user-images.githubusercontent.com/48039235/210697003-8e68385b-ff47-44de-8bda-79affee8e386.png)
- commands at peak times
![image](https://user-images.githubusercontent.com/48039235/210697216-ef935e7c-4076-4ec6-ac89-f00672d24c5d.png)
- all commands:
![image](https://user-images.githubusercontent.com/48039235/210698352-5d5b49ad-d5bf-444d-8668-4eef0777334b.png)

- the number of requests:
![image](https://user-images.githubusercontent.com/48039235/210697443-f743e4e9-1613-4de9-bb0c-ab38db5140b3.png)
- **although, the number of connections of the tenant to the redis proxy is approximate < 100 connections**

### 2. Configurations
```yaml
- Camellia version: 1.1.8
- Redis resource: redis cluster
```

@caojiajun, pls help me check this issue. Thank you

**Comment by tasszz2k** [comment]
@caojiajun , pls help me check this issue

**Comment by tasszz2k** [comment]
**this is a critical bug**

**Comment by caojiajun** [comment]
execute this command to proxy `info upstream`

**Comment by tasszz2k** [comment]
> execute this command to proxy `info upstream`

```
# Upstream
upstream_redis_nums:6503
upstream_redis_nums[@xxx.xx.xxx.xxx:6379]:3
upstream_redis_nums[@xxx.xx.xxx.xxx:6379]:2135
upstream_redis_nums[@xxx.xx.xxx.xxx:6379]:2139
upstream_redis_nums[@xxx.xx.xxx.xxx:6379]:6
upstream_redis_nums[@xxx.xx.xxx.xxx:6379]:2171
upstream_redis_nums[@xxx.xx.xxx.xxx:6379]:8
upstream_redis_nums[@xxx.xx.xxx.xxx:6379]:8
upstream_redis_nums[@rfs-redis-sentinel-1.redis-sentinel-1.svc:26379]:1
upstream_redis_nums[@xxx.xx.xxx.xxx:6379]:3
upstream_redis_nums[@xxx.xx.xxx.xxx:6379]:8
upstream_redis_nums[@xxx.xx.xxx.xxx:6379]:8
upstream_redis_nums[@xxx.xx.xxx.xxx:6379]:4
upstream_redis_nums[@xxx.xx.xxx.xxx:6379]:3
upstream_redis_nums[@xxx.xx.xxx.xxx:6379]:6
```

**Comment by caojiajun** [comment]
pls provide the `application.yml` and proxy log

**Comment by tasszz2k** [comment]
Can you help me explain the mechanism that handles the connection of the redis proxy from clients and the "real" connection to redis resources?
Is it mapped 1-1 or n-1?
Is 1 connection from the client always creating one to redis or reuse it from a cache (`ConcurrentHashMap<String, RedisClient> map`)?

**Comment by tasszz2k** [comment]
> pls provide the `application.yml` and proxy log

```yaml
  application.yml: |
    server:
      port: 6380
    spring:
      application:
        name: camellia-redis-proxy-server
    
    camellia-redis-proxy:
      console-port: 16379
      monitor-enable: true
      monitor-interval-seconds: 60
      client-auth-provider-class-name: xx.xx.camellia.redis.proxy.auth.MultiTenantAuthProvider
      plugins: #
        - monitorPlugin
        - converterPlugin
        - dynamicIpCheckerPlugin
      transpond:
        type: remote
        remote:
          url: https://dev-camellia-dashboard.xx.xx
          check-interval-millis: 5000
          dynamic: true
          header-map:
            api-key: xxxxxx
  camellia-redis-proxy.properties: |
    dynamic.conf.file.path=/apps/camellia-redis-proxy.properties
    dynamic.conf.reload.interval.seconds=10
    dynamic.ip.check.plugin.config.update.interval.seconds=5
    camellia.dashboard.url=https://dev-camellia-dashboard.xx.xx
    camellia.dashboard.headerMap={"api-key": "xxxxxx"}
    converter.key.className=xx.xx.camellia.redis.proxy.converter.TenancyNamespaceKeyForRedisClusterCRC16Converter


```
