### ISSUE TITLE
should support epoll in linux and add quickack option

### ISSUE THREAD

**Issue by tain198127** [netease-im/camellia#87]
Module: [camellia-redis-proxy]
Content: [need support epoll in linux and add quickackoption]
I found the camellia-redis-proxy online support nio selector. when run in linux system, epoll mode is more efficient than Nio.
we should use epoll mode in linux and use quickack tcp option.

**Comment by caojiajun** [comment]
when `camellia-redis-proxy` run in linux system, netty nio default use epoll. you can use `jstack` to confirm, like this:
```
"camellia-work-group-3-1" #52 prio=5 os_prio=0 tid=0x00007fecdc16e800 nid=0x1030c runnable [0x00007fecbc5e9000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x00000000c0cadc10> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x00000000c0cadc28> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000000c0cadbc8> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:810)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

```

the `quickack` tcp option will support in next version (`1.1.12`）

**Comment by tain198127** [comment]
assign me ,thx! I just log this issue

**Comment by caojiajun** [comment]
> assign me ,thx! I just log this issue

could you pls check the performance difference between `enable` and `disable` of  `TCP_QUICKACK` option

**Comment by caojiajun** [comment]
you can enable `TCP_QUICKACK` like this, proxy version `1.1.12-SNAPSHOT`
```
camellia-redis-proxy:
  #tcp connect between client and proxy
  netty:
    tcp-quick-ack: true #default false
  transpond:
    type: local
    local:
      resource: redis://@127.0.0.1:6379
    #tcp connect between proxy and redis
    netty:
      tcp-quick-ack: true #default false
```

**Comment by caojiajun** [comment]
tcp_quickack option will support in `1.1.13`
`1.1.12` will be a hotfix version

**Comment by tain198127** [comment]
> > assign me ,thx! I just log this issue
> 
> could you pls check the performance difference between `enable` and `disable` of `TCP_QUICKACK` option
If disable quickact  tcp option, in NFT test environment, will delay around 40ms ,especially with small kv  test case. We found that problem in dubbo netty module, so we review the code of camellia code, and found the same problem.

**Comment by caojiajun** [comment]
> > > assign me ,thx! I just log this issue
> > 
> > 
> > could you pls check the performance difference between `enable` and `disable` of `TCP_QUICKACK` option
> 
> If disable quickact tcp option, in NFT test environment, will delay around 40ms ,especially with small kv test case. We found that problem in dubbo netty module, so we review the code of camellia code, and found the same problem.

ok, `1.1.13` will support setting this option, and the default configuration depends on the test results

**Comment by tain198127** [comment]
> > > > assign me ,thx! I just log this issue
> > > 
> > > 
> > > could you pls check the performance difference between `enable` and `disable` of `TCP_QUICKACK` option
> > 
> > 
> > If disable quickact tcp option, in NFT test environment, will delay around 40ms ,especially with small kv test case. We found that problem in dubbo netty module, so we review the code of camellia code, and found the same problem.
> 
> ok, `1.1.13` will support setting this option, and the default configuration depends on the test results

OK, BTW, it's need add quick_ack option EVERY time after read function of netty ,otherwise several times quick_ack will not works.  And inbound and outbound both side need set quick_ack option.

**Comment by caojiajun** [comment]
the full netty-conf: 
https://github.com/netease-im/camellia/blob/master/docs/redis-proxy/other/netty-conf.md

**Comment by tain198127** [comment]
# 1. Test ENV:

## 1.1 hardware

2C 4G aliyun

## 1.2 system:

LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core) 
Release:        7.6.1810
Codename:       Core

## 1.3 jdk version

```
java version "11.0.16.1" 2022-08-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.16.1+1-LTS-1)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.16.1+1-LTS-1, mixed mode)
```



## 1.4 redis-info

**redis_version:6.2.7**

```
# Server
redis_version:6.2.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:3610f9cc462a06b9
redis_mode:cluster
os:Linux 3.10.0-957.21.3.el7.x86_64 x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:4.8.5
process_id:8598
process_supervised:no
run_id:dbbb5f66244d7792ff6e8cb65bb8c97367115d52
tcp_port:6380
server_time_usec:1673893296220723
uptime_in_seconds:6010
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:12948912
executable:/xxxxxx/redis-server
config_file:/xxxxxx/./redis-6.2.7/redis.conf
io_threads_active:0

# Memory
used_memory:1642296
used_memory_human:1.57M
used_memory_rss:12197888
used_memory_rss_human:11.63M
used_memory_peak:1700272
used_memory_peak_human:1.62M
used_memory_peak_perc:96.59%
used_memory_overhead:1484240
used_memory_startup:1484016
used_memory_dataset:158056
used_memory_dataset_perc:99.86%
allocator_allocated:1651680
allocator_active:1994752
allocator_resident:4493312
total_system_memory:3823378432
total_system_memory_human:3.56G
used_memory_lua:32768
used_memory_lua_human:32.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.21
allocator_frag_bytes:343072
allocator_rss_ratio:2.25
allocator_rss_bytes:2498560
rss_overhead_ratio:2.71
rss_overhead_bytes:7704576
mem_fragmentation_ratio:7.73
mem_fragmentation_bytes:10619304
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:0
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0
```

## 1.5 cluster-info

```
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:6
cluster_my_epoch:1
cluster_stats_messages_ping_sent:6021
cluster_stats_messages_pong_sent:6029
cluster_stats_messages_sent:12050
cluster_stats_messages_ping_received:6029
cluster_stats_messages_pong_received:6021
cluster_stats_messages_received:12050

```



## 1.6 cluster-node

```
64528c1147d8abfa7021d060aacadfbd742d9ce0 XXX.XXX.XXX.95:6380@16380 myself,slave 690ab458ecf08291cebe4e660dad62863c1021fc 0 1673893577000 1 connected
d6d79f9ba4f7368d63fe47748d32919be6f163b6 XXX.XXX.XXX.94:6380@16380 slave 592470f526f6fc38f4a9c00322b742a577092bdf 0 1673893577623 5 connected
592470f526f6fc38f4a9c00322b742a577092bdf XXX.XXX.XXX.96:6379@16379 master - 0 1673893576000 5 connected 10923-16383
690ab458ecf08291cebe4e660dad62863c1021fc XXX.XXX.XXX.94:6379@16379 master - 0 1673893573612 1 connected 0-5460
d67bbd15aa840067b663292c4809ab992e04b84f XXX.XXX.XXX.95:6379@16379 master - 0 1673893577000 3 connected 5461-10922
d031a023e4ecf342bc52d2f23ef803978267f7c3 XXX.XXX.XXX.96:6380@16380 slave d67bbd15aa840067b663292c4809ab992e04b84f 0 1673893576000 3 connected

```

---



# 2. camellia-proxy-sample config

Only has two difference ,which was **camellia-redis-proxy.netty.tcp-quick-ack** and **camellia-redis-proxy.transpond.netty.tcp-quick-ack** be set **true/false**

## 2.1 by proxy and quick ack

```yaml
server:
  port: 26380
spring:
  application:
    name: camellia-redis-proxy-server

camellia-redis-proxy:
  console-port: 16379
  password: pass123
  monitor-enable: false  #monitor enable/disable configure
  monitor-interval-seconds: 60
  netty-transport-mode: epoll
  plugins: #plugin list
    - monitorPlugin
    - bigKeyPlugin
    - hotKeyPlugin
  transpond:
    type: local #local、remote、custom
    local:
      type: simple #simple、complex
      resource: redis-cluster://PASSWORD@XXX.XXX.XXX.95:6379,XXX.XXX.XXX.95:6380,XXX.XXX.XXX.94:6379,XXX.XXX.XXX.94:6380,XXX.XXX.XXX.96:6379,XXX.XXX.XXX.96:6380
    netty:
      tcpQuickAck: true
  netty:
    tcp-quick-ack: true
```

## 2.2 without quickack

```yaml
server:
  port: 26380
spring:
  application:
    name: camellia-redis-proxy-server

camellia-redis-proxy:
  console-port: 16379
  password: pass123
  monitor-enable: false  #monitor enable/disable configure
  monitor-interval-seconds: 60
  netty-transport-mode: epoll
  plugins: #plugin list
    - monitorPlugin
    - bigKeyPlugin
    - hotKeyPlugin
  transpond:
    type: local #local、remote、custom
    local:
      type: simple #simple、complex
      resource: redis-cluster://PASSWORD@XXX.XXX.XXX.95:6379,XXX.XXX.XXX.95:6380,XXX.XXX.XXX.94:6379,XXX.XXX.XXX.94:6380,XXX.XXX.XXX.96:6379,XXX.XXX.XXX.96:6380
    netty:
      tcpQuickAck: false
  netty:
    tcp-quick-ack: false
```



## 2.3 application starupu param

proxy:

```java -jar camellia-redis-proxy-samples-1.1.13-SNAPSHOT.jar ```

redis:

```
default
```



**[NOTE]**: If some one want get more efficiency, you can change xmx,xms,gc-type  and the other jvm optimize param suit for you environment. And optimize redis config as well.



# 3. TestCase

## 3.1 by proxy and quick ack

```redis-benchmark -r 10000 -n 10000 -h XXX.XXX.XXX.95 -p 26380 -c 20 -t get -a pass123 -d 400```

result:

| test | rps      | avg_latency_ms | min_latency_ms | p50_latency_ms | p95_latency_ms | p99_latency_ms | max_latency_ms |
| ---- | -------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- |
| GET  | 15384.62 | 1.191          | 0.176          | 0.695          | 4.599          | 7.975          | 17.055         |

## 3.2 without quickack

```redis-benchmark -r 10000 -n 10000 -h XXX.XXX.XXX.94 -p 26380 -c 20 -t get -a pass123 -d 400```

result:

| test | rps      | avg_latency_ms | min_latency_ms | p50_latency_ms | p95_latency_ms | p99_latency_ms | max_latency_ms |
| ---- | -------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- |
| GET  | 10050.25 | 1.869          | 0.16           | 0.951          | 6.671          | 10.583         | 21.087         |

## 3.3 direct redis-cluster

```redis-benchmark -r 10000 -n 10000 -h XXX.XXX.XXX.95 -p 6380 -c 20 -t get -a Bd1981@7 -d 400 --cluster```

result:

| test | rps      | avg_latency_ms | min_latency_ms | p50_latency_ms | p95_latency_ms | p99_latency_ms | max_latency_ms |
| ---- | -------- | -------------- | -------------- | -------------- | -------------- | -------------- | -------------- |
| GET  | 19801.98 | 0.673          | 0.088          | 0.303          | 2.791          | 7.655          | 15.615         |



# 4. conclusion

Turn on tcp-quick-ack and use epoll mode in Linux was more efficiency. Which means lower RT and higher TPS at same time. Although use camellia-redis-proxy not fast enough than direct access redis-cluster,but it will be shirk connections from clients to redis-cluster especially in larg scale redis-cluster environment.
